import { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { projectsApi } from '../../api/projects'
import { tasksApi } from '../../api/tasks'
import Badge from '../../components/ui/Badge'
import Button from '../../components/ui/Button'
import Modal from '../../components/ui/Modal'
import Input from '../../components/ui/Input'
import EditProjectModal from '../../components/ui/EditProjectModal'
import EditTaskModal from '../../components/ui/EditTaskModal'
import toast from 'react-hot-toast'
import ActivityLog from '../../components/ui/ActivityLog'

const STATUS_COLUMNS = [
  { key: 'todo', label: 'To Do', color: 'bg-gray-100' },
  { key: 'in_progress', label: 'In Progress', color: 'bg-blue-100' },
  { key: 'done', label: 'Done', color: 'bg-green-100' },
]

export default function ProjectPage() {
  const { projectId } = useParams()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const [isCreateTaskOpen, setIsCreateTaskOpen] = useState(false)
  const [isEditProjectOpen, setIsEditProjectOpen] = useState(false)
  const [isDeleteConfirmOpen, setIsDeleteConfirmOpen] = useState(false)
  const [isEditTaskOpen, setIsEditTaskOpen] = useState(false)
  const [selectedTask, setSelectedTask] = useState(null)
  const [taskForm, setTaskForm] = useState({ title: '', description: '', priority: 'medium' })
  const [isGenerating, setIsGenerating] = useState(false)

  const { data: projectData } = useQuery({
    queryKey: ['project', projectId],
    queryFn: () => projectsApi.getById(projectId),
  })

  const { data: tasksData, isLoading } = useQuery({
    queryKey: ['tasks', projectId],
    queryFn: () => tasksApi.getAll(projectId, { limit: 100 }),
  })

  const project = projectData?.data
  const tasks = tasksData?.data?.items || []

  const createTask = useMutation({
    mutationFn: () => tasksApi.create(projectId, taskForm),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks', projectId] })
      queryClient.invalidateQueries({ queryKey: ['activities', projectId] })
      setTaskForm({ title: '', description: '', priority: 'medium' })
      setIsCreateTaskOpen(false)
      toast.success('Task created!')
    },
    onError: (err) => {
      toast.error(err.response?.data?.error?.message || 'Failed to create task')
    },
  })

  const updateTaskStatus = useMutation({
    mutationFn: ({ taskId, status }) => tasksApi.update(projectId, taskId, { status }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks', projectId] })
      queryClient.invalidateQueries({ queryKey: ['activities', projectId] })
      toast.success('Task updated!')
    },
    onError: () => toast.error('Failed to update task'),
  })

  const deleteTask = useMutation({
    mutationFn: (taskId) => tasksApi.delete(projectId, taskId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks', projectId] })
      queryClient.invalidateQueries({ queryKey: ['activities', projectId] })
      toast.success('Task deleted!')
    },
    onError: () => toast.error('Failed to delete task'),
  })

  const deleteProject = useMutation({
    mutationFn: () => projectsApi.delete(projectId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['projects'] })
      toast.success('Project deleted!')
      navigate('/dashboard')
    },
    onError: () => toast.error('Failed to delete project'),
  })

  const handleGenerateAI = async () => {
  setIsGenerating(true)
  try {
    const result = await tasksApi.generateTasks(projectId)
    queryClient.invalidateQueries({ queryKey: ['tasks', projectId] })
    toast.success(`${result.data.generated} tasks generated by AI!`)
  } catch {
    toast.error('Failed to generate tasks')
  } finally {
    setIsGenerating(false)
  }
}

  const getTasksByStatus = (status) =>
    tasks.filter((t) => t.status === status)

  if (!project) return null

  return (
    <div className="p-8">
      {/* Header */}
      <div className="flex items-center gap-4 mb-8">
        <button
          onClick={() => navigate('/dashboard')}
          className="text-gray-400 hover:text-gray-600 transition-colors"
        >
          ← Back
        </button>
        <div className="flex-1">
          <h1 className="text-2xl font-bold text-gray-900">{project.name}</h1>
          {project.description && (
            <p className="text-gray-500 mt-1">{project.description}</p>
          )}
        </div>
        <div className="flex gap-2">
          <Button variant="secondary" onClick={() => setIsEditProjectOpen(true)}>
            ✏️ Edit
          </Button>
          <Button variant="secondary" onClick={handleGenerateAI} isLoading={isGenerating}>
            🤖 AI Tasks
          </Button>
          <Button onClick={() => setIsCreateTaskOpen(true)}>
            + Add Task
          </Button>
          <Button variant="danger" onClick={() => setIsDeleteConfirmOpen(true)}>
            🗑️
          </Button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-4 mb-8">
        {STATUS_COLUMNS.map((col) => (
          <div key={col.key} className="bg-white rounded-xl border border-gray-200 p-4">
            <p className="text-sm text-gray-500">{col.label}</p>
            <p className="text-2xl font-bold text-gray-900 mt-1">
              {getTasksByStatus(col.key).length}
            </p>
          </div>
        ))}
      </div>

      {/* Main Content — Kanban + Activity Log */}
      <div className="flex gap-6">
        {/* Kanban Board */}
        <div className="flex-1">
          {isLoading ? (
            <div className="text-center py-12 text-gray-400">Loading tasks...</div>
          ) : (
            <div className="grid grid-cols-3 gap-6">
              {STATUS_COLUMNS.map((col) => (
                <div key={col.key}>
                  <div className={`${col.color} rounded-lg p-3 mb-3`}>
                    <h3 className="font-medium text-gray-700 text-sm">
                      {col.label}
                      <span className="ml-2 text-gray-500">
                        ({getTasksByStatus(col.key).length})
                      </span>
                    </h3>
                  </div>
                  <div className="space-y-3">
                    {getTasksByStatus(col.key).map((task) => (
                      <div
                        key={task.id}
                        className="bg-white rounded-xl border border-gray-200 p-4 hover:shadow-md transition-shadow"
                      >
                        <div className="flex items-start justify-between gap-2 mb-2">
                          <p className="text-sm font-medium text-gray-900 flex-1">
                            {task.title}
                          </p>
                          <Badge variant={task.priority}>{task.priority}</Badge>
                        </div>

                        {task.description && (
                          <p className="text-xs text-gray-500 mb-3 line-clamp-2">
                            {task.description}
                          </p>
                        )}

                        {task.due_date && (
                          <p className="text-xs text-gray-400 mb-3">
                            📅 {new Date(task.due_date).toLocaleDateString('en-US', {
                              month: 'short', day: 'numeric', year: 'numeric'
                            })}
                          </p>
                        )}

                        <div className="flex gap-1 flex-wrap">
                          {STATUS_COLUMNS.filter((s) => s.key !== task.status).map((s) => (
                            <button
                              key={s.key}
                              onClick={() => updateTaskStatus.mutate({ taskId: task.id, status: s.key })}
                              className="text-xs px-2 py-1 rounded bg-gray-100 text-gray-600 hover:bg-indigo-100 hover:text-indigo-600 transition-colors"
                            >
                              {s.label}
                            </button>
                          ))}
                          <div className="ml-auto flex gap-1">
                            <button
                              onClick={() => { setSelectedTask(task); setIsEditTaskOpen(true) }}
                              className="text-xs px-2 py-1 rounded bg-gray-100 text-gray-600 hover:bg-indigo-100 hover:text-indigo-600 transition-colors"
                            >
                              ✏️
                            </button>
                            <button
                              onClick={() => deleteTask.mutate(task.id)}
                              className="text-xs px-2 py-1 rounded bg-gray-100 text-red-500 hover:bg-red-50 transition-colors"
                            >
                              🗑️
                            </button>
                          </div>
                        </div>
                      </div>
                    ))}

                    {getTasksByStatus(col.key).length === 0 && (
                      <div className="text-center py-8 text-gray-400 text-sm border-2 border-dashed border-gray-200 rounded-xl">
                        No tasks
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Activity Log Sidebar */}
        <div className="w-72 flex-shrink-0">
          <div className="bg-white rounded-xl border border-gray-200 p-4 sticky top-8">
            <h3 className="font-semibold text-gray-900 mb-4">📋 Activity Log</h3>
            <ActivityLog projectId={projectId} />
          </div>
        </div>
      </div>

      {/* Modals */}
      <EditProjectModal
        isOpen={isEditProjectOpen}
        onClose={() => setIsEditProjectOpen(false)}
        project={project}
      />
      <Modal
        isOpen={isDeleteConfirmOpen}
        onClose={() => setIsDeleteConfirmOpen(false)}
        title="Delete Project"
      >
        <p className="text-gray-600 mb-6">
          Are you sure you want to delete <strong>{project.name}</strong>?
          This will also delete all tasks. This action cannot be undone.
        </p>
        <div className="flex gap-3 justify-end">
          <Button variant="secondary" onClick={() => setIsDeleteConfirmOpen(false)}>
            Cancel
          </Button>
          <Button
            variant="danger"
            isLoading={deleteProject.isPending}
            onClick={() => deleteProject.mutate()}
          >
            Delete Project
          </Button>
        </div>
      </Modal>
      <Modal
        isOpen={isCreateTaskOpen}
        onClose={() => setIsCreateTaskOpen(false)}
        title="Create New Task"
      >
        <form
          onSubmit={(e) => { e.preventDefault(); createTask.mutate() }}
          className="space-y-4"
        >
          <Input
            label="Task Title"
            placeholder="What needs to be done?"
            value={taskForm.title}
            onChange={(e) => setTaskForm({ ...taskForm, title: e.target.value })}
            required
          />
          <div className="space-y-1">
            <label className="block text-sm font-medium text-gray-700">
              Description (optional)
            </label>
            <textarea
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 resize-none"
              rows={3}
              placeholder="Add more details..."
              value={taskForm.description}
              onChange={(e) => setTaskForm({ ...taskForm, description: e.target.value })}
            />
          </div>
          <div className="space-y-1">
            <label className="block text-sm font-medium text-gray-700">Priority</label>
            <select
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
              value={taskForm.priority}
              onChange={(e) => setTaskForm({ ...taskForm, priority: e.target.value })}
            >
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
            </select>
          </div>
          <div className="flex gap-3 justify-end">
            <Button variant="secondary" type="button" onClick={() => setIsCreateTaskOpen(false)}>
              Cancel
            </Button>
            <Button type="submit" isLoading={createTask.isPending}>
              Create Task
            </Button>
          </div>
        </form>
      </Modal>
      <EditTaskModal
        isOpen={isEditTaskOpen}
        onClose={() => { setIsEditTaskOpen(false); setSelectedTask(null) }}
        task={selectedTask}
        projectId={projectId}
      />
    </div>
  )
}